cellsociety_team09: application.WaTorCell2 Class Reference
application.WaTorCell2 Class Reference
Public Member Functions
void updateCell (int i, int j, Cell[][] cellMatrix)
Public Member Functions inherited from application.Cell
void setThreshold (double num)
String toString ()
Private Member Functions
void updateState ()
void updateShark ()
void moveShark ()
void checkTimeTillSharkEvents (WaTorCell2 cell)
void killShark (WaTorCell2 cell)
void updateFish ()
void checkTimeTillFishBreeding (WaTorCell2 cell)
void breed (WaTorCell2 cell, Color color)
ArrayList findNeighbors (int i, int j, Color color)
boolean checkBounds (int i, int j)
void initializeNewCell (WaTorCell2 cell)
void populateOtherCell (WaTorCell2 cell)
Private Attributes
int fishTimeTillBreedingParameter = 3
int sharkTimeTillDeathParameter = 3
int sharkTimeTillBreedingParameter = 3
int fishTimeTillBreeding = fishTimeTillBreedingParameter
int sharkTimeTillDeath = sharkTimeTillDeathParameter
int sharkTimeTillBreeding = sharkTimeTillBreedingParameter
Additional Inherited Members
Protected Member Functions inherited from application.Cell
abstract void updateCell (int i, int j, Cell[][] cellMatrix)
List findWantedNeighbors (Color color)
List findWantedNeighbors (Color currentColor, Color updatedColor)
List findWantedNeighbors (Cell otherCell, Color currentColor, Color updatedColor)
Package Functions inherited from application.Cell
void update ()
void setCurrentState (Color color)
void setXPos (int x)
void setYPos (int y)
void setGridEdgeType (String s)
void setGridLocationShape (String s)
Package Attributes inherited from application.Cell
int xPos
int yPos
Paint currentState
Paint updatedState
double threshold
String gridEdgeType
String gridLocationShape
Cell[][] Matrix
Map< Integer, Cell > neighbors = new HashMap<Integer, Cell>()
int cellID
Detailed Description
Definition at line 9 of file WaTorCell2.java.
Member Function Documentation
void application.WaTorCell2.breed (WaTorCell2 cell, Color color) private
Definition at line 114 of file WaTorCell2.java.
References application.WaTorCell2.findNeighbors(), application.WaTorCell2.initializeNewCell(), application.Cell.xPos, and application.Cell.yPos.
Referenced by application.WaTorCell2.checkTimeTillFishBreeding(), and application.WaTorCell2.checkTimeTillSharkEvents().
boolean application.WaTorCell2.checkBounds (int i, int j) private
Definition at line 154 of file WaTorCell2.java.
Referenced by application.WaTorCell2.findNeighbors().
void application.WaTorCell2.checkTimeTillFishBreeding (WaTorCell2 cell) private
Definition at line 104 of file WaTorCell2.java.
References application.WaTorCell2.breed(), application.WaTorCell2.fishTimeTillBreeding, and application.WaTorCell2.fishTimeTillBreedingParameter.
Referenced by application.WaTorCell2.updateFish().
void application.WaTorCell2.checkTimeTillSharkEvents (WaTorCell2 cell) private
Definition at line 71 of file WaTorCell2.java.
References application.WaTorCell2.breed(), application.WaTorCell2.killShark(), application.WaTorCell2.sharkTimeTillBreeding, application.WaTorCell2.sharkTimeTillBreedingParameter, and application.WaTorCell2.sharkTimeTillDeath.
Referenced by application.WaTorCell2.moveShark().
ArrayList application.WaTorCell2.findNeighbors (int i, int j, Color color) private
Definition at line 126 of file WaTorCell2.java.
References application.WaTorCell2.checkBounds(), application.Cell.currentState, application.Cell.Matrix, and application.Cell.updatedState.
Referenced by application.WaTorCell2.breed(), application.WaTorCell2.moveShark(), application.WaTorCell2.updateFish(), and application.WaTorCell2.updateShark().
void application.WaTorCell2.initializeNewCell (WaTorCell2 cell) private
Definition at line 158 of file WaTorCell2.java.
References application.WaTorCell2.fishTimeTillBreeding, application.WaTorCell2.fishTimeTillBreedingParameter, application.WaTorCell2.sharkTimeTillBreeding, application.WaTorCell2.sharkTimeTillBreedingParameter, application.WaTorCell2.sharkTimeTillDeath, and application.WaTorCell2.sharkTimeTillDeathParameter.
Referenced by application.WaTorCell2.breed().
void application.WaTorCell2.killShark (WaTorCell2 cell) private
Definition at line 80 of file WaTorCell2.java.
References application.Cell.updatedState.
Referenced by application.WaTorCell2.checkTimeTillSharkEvents().
void application.WaTorCell2.moveShark () private
Definition at line 52 of file WaTorCell2.java.
References application.WaTorCell2.checkTimeTillSharkEvents(), application.WaTorCell2.findNeighbors(), application.WaTorCell2.populateOtherCell(), application.Cell.updatedState, application.Cell.xPos, and application.Cell.yPos.
Referenced by application.WaTorCell2.updateShark().
void application.WaTorCell2.populateOtherCell (WaTorCell2 cell) private
Definition at line 164 of file WaTorCell2.java.
References application.WaTorCell2.fishTimeTillBreeding, application.WaTorCell2.sharkTimeTillBreeding, and application.WaTorCell2.sharkTimeTillDeath.
Referenced by application.WaTorCell2.moveShark(), and application.WaTorCell2.updateFish().
void application.WaTorCell2.updateCell (int i, int j, Cell cellMatrix[][])
Definition at line 20 of file WaTorCell2.java.
References application.Cell.Matrix, application.WaTorCell2.updateState(), application.Cell.xPos, and application.Cell.yPos.
void application.WaTorCell2.updateFish () private
Definition at line 86 of file WaTorCell2.java.
References application.WaTorCell2.checkTimeTillFishBreeding(), application.Cell.currentState, application.WaTorCell2.findNeighbors(), application.WaTorCell2.populateOtherCell(), application.Cell.updatedState, application.Cell.xPos, and application.Cell.yPos.
Referenced by application.WaTorCell2.updateState().
void application.WaTorCell2.updateShark () private
Definition at line 39 of file WaTorCell2.java.
References application.Cell.currentState, application.WaTorCell2.findNeighbors(), application.WaTorCell2.moveShark(), application.WaTorCell2.sharkTimeTillDeathParameter, application.Cell.updatedState, application.Cell.xPos, and application.Cell.yPos.
Referenced by application.WaTorCell2.updateState().
void application.WaTorCell2.updateState () private
Definition at line 27 of file WaTorCell2.java.
References application.Cell.currentState, application.Cell.updatedState, application.WaTorCell2.updateFish(), and application.WaTorCell2.updateShark().
Referenced by application.WaTorCell2.updateCell().
Member Data Documentation
int application.WaTorCell2.fishTimeTillBreeding = fishTimeTillBreedingParameter private
Definition at line 15 of file WaTorCell2.java.
Referenced by application.WaTorCell2.checkTimeTillFishBreeding(), application.WaTorCell2.initializeNewCell(), and application.WaTorCell2.populateOtherCell().
int application.WaTorCell2.fishTimeTillBreedingParameter = 3 private
Definition at line 11 of file WaTorCell2.java.
Referenced by application.WaTorCell2.checkTimeTillFishBreeding(), and application.WaTorCell2.initializeNewCell().
int application.WaTorCell2.sharkTimeTillBreeding = sharkTimeTillBreedingParameter private
Definition at line 17 of file WaTorCell2.java.
Referenced by application.WaTorCell2.checkTimeTillSharkEvents(), application.WaTorCell2.initializeNewCell(), and application.WaTorCell2.populateOtherCell().
int application.WaTorCell2.sharkTimeTillBreedingParameter = 3 private
Definition at line 13 of file WaTorCell2.java.
Referenced by application.WaTorCell2.checkTimeTillSharkEvents(), and application.WaTorCell2.initializeNewCell().
int application.WaTorCell2.sharkTimeTillDeath = sharkTimeTillDeathParameter private
Definition at line 16 of file WaTorCell2.java.
Referenced by application.WaTorCell2.checkTimeTillSharkEvents(), application.WaTorCell2.initializeNewCell(), and application.WaTorCell2.populateOtherCell().
int application.WaTorCell2.sharkTimeTillDeathParameter = 3 private
Definition at line 12 of file WaTorCell2.java.
Referenced by application.WaTorCell2.initializeNewCell(), and application.WaTorCell2.updateShark().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/WaTorCell2.java