cellsociety_team09: application.FloodCell Class Reference
application.FloodCell Class Reference
Protected Member Functions
void updateCell (int i, int j, Cell[][] cellMatrix)
Protected Member Functions inherited from application.Cell
abstract void updateCell (int i, int j, Cell[][] cellMatrix)
List findWantedNeighbors (Color color)
List findWantedNeighbors (Color currentColor, Color updatedColor)
List findWantedNeighbors (Cell otherCell, Color currentColor, Color updatedColor)
Private Member Functions
void floodSelf ()
void setUpdatedState ()
Private Attributes
boolean OKToFlood = false
List< WaTorCell > neighborsList = new ArrayList<WaTorCell>()
Additional Inherited Members
Public Member Functions inherited from application.Cell
void setThreshold (double num)
String toString ()
Package Functions inherited from application.Cell
void update ()
void setCurrentState (Color color)
void setXPos (int x)
void setYPos (int y)
void setGridEdgeType (String s)
void setGridLocationShape (String s)
Package Attributes inherited from application.Cell
int xPos
int yPos
Paint currentState
Paint updatedState
double threshold
String gridEdgeType
String gridLocationShape
Cell[][] Matrix
Map< Integer, Cell > neighbors = new HashMap<Integer, Cell>()
int cellID
Detailed Description
Version 1 Date: 9/25/2014
Used for simple grid tests and neighbor logic testing Floods the grid with a certain color
Author
Michael Deng
Pranava Raparla
David Zhang
Definition at line 19 of file FloodCell.java.
Member Function Documentation
void application.FloodCell.floodSelf () private
Checks to see if the current cell is next to a flooded cell If so, flood the current cell
Definition at line 39 of file FloodCell.java.
References application.Cell.findWantedNeighbors(), and application.FloodCell.setUpdatedState().
Referenced by application.FloodCell.updateCell().
void application.FloodCell.setUpdatedState () private
Flood the current cell if it should be flooded
Definition at line 49 of file FloodCell.java.
References application.Cell.currentState, and application.Cell.updatedState.
Referenced by application.FloodCell.floodSelf().
void application.FloodCell.updateCell (int i, int j, Cell cellMatrix[][]) protected
Updates the state of the cell
Definition at line 28 of file FloodCell.java.
References application.FloodCell.floodSelf(), application.Cell.xPos, and application.Cell.yPos.
Member Data Documentation
List<WaTorCell> application.FloodCell.neighborsList = new ArrayList<WaTorCell>() private
Definition at line 22 of file FloodCell.java.
boolean application.FloodCell.OKToFlood = false private
Definition at line 21 of file FloodCell.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/FloodCell.java