cellsociety_team09: application.FireCell Class Reference
application.FireCell Class Reference
Protected Member Functions
void updateCell (int i, int j, Cell[][] cellMatrix)
Protected Member Functions inherited from application.Cell
abstract void updateCell (int i, int j, Cell[][] cellMatrix)
List findWantedNeighbors (Color color)
List findWantedNeighbors (Color currentColor, Color updatedColor)
List findWantedNeighbors (Cell otherCell, Color currentColor, Color updatedColor)
Private Member Functions
void findFireNeighbors ()
void calculateBurnChance ()
void updateState ()
Private Attributes
Boolean isNextToFire = false
double threshold = 0
List< Cell > fireNeighbors = new ArrayList<Cell>()
Additional Inherited Members
Public Member Functions inherited from application.Cell
void setThreshold (double num)
String toString ()
Package Functions inherited from application.Cell
void update ()
void setCurrentState (Color color)
void setXPos (int x)
void setYPos (int y)
void setGridEdgeType (String s)
void setGridLocationShape (String s)
Package Attributes inherited from application.Cell
int xPos
int yPos
Paint currentState
Paint updatedState
double threshold
String gridEdgeType
String gridLocationShape
Cell[][] Matrix
Map< Integer, Cell > neighbors = new HashMap<Integer, Cell>()
int cellID
Detailed Description
Version 1 Date: 9/14/2014
Author
Michael Deng
Pranava Raparla
David Zhang
Definition at line 18 of file FireCell.java.
Member Function Documentation
void application.FireCell.calculateBurnChance () private
Calculates the chance of the current cell burning
Definition at line 39 of file FireCell.java.
Referenced by application.FireCell.updateCell().
void application.FireCell.findFireNeighbors () private
Find if any of the neighbors are on fire
Definition at line 28 of file FireCell.java.
References application.Cell.findWantedNeighbors().
Referenced by application.FireCell.updateCell().
void application.FireCell.updateCell (int i, int j, Cell cellMatrix[][]) protected
Definition at line 63 of file FireCell.java.
References application.FireCell.calculateBurnChance(), application.FireCell.findFireNeighbors(), and application.FireCell.updateState().
void application.FireCell.updateState () private
Updates the state of the cell based off of the burning chance
Definition at line 51 of file FireCell.java.
References application.ApplicationConstants.rand, and application.FireCell.threshold.
Referenced by application.FireCell.updateCell().
Member Data Documentation
List<Cell> application.FireCell.fireNeighbors = new ArrayList<Cell>() private
Definition at line 23 of file FireCell.java.
Boolean application.FireCell.isNextToFire = false private
Definition at line 20 of file FireCell.java.
double application.FireCell.threshold = 0 private
Definition at line 21 of file FireCell.java.
Referenced by application.FireCell.updateState().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/FireCell.java