cellsociety_team09: application.AntCell2 Class Reference
application.AntCell2 Class Reference
Protected Member Functions
void updateCell (int i, int j, Cell[][] cellMatrix)
Protected Member Functions inherited from application.Cell
abstract void updateCell (int i, int j, Cell[][] cellMatrix)
List findWantedNeighbors (Color color)
List findWantedNeighbors (Color currentColor, Color updatedColor)
List findWantedNeighbors (Cell otherCell, Color currentColor, Color updatedColor)
Private Member Functions
void antForage ()
void goHome (AntCell2 cell)
Private Attributes
boolean hasFood = false
int Orientation
int homePheromones
int foodPheromones
int newOrientation
int pheromoneConstant = 3
int largestPheromone
List< AntCell2 > moveForwardList = new ArrayList<AntCell2>()
List< AntCell2 > pheromoneList = new ArrayList<AntCell2>()
Additional Inherited Members
Public Member Functions inherited from application.Cell
void setThreshold (double num)
String toString ()
Package Functions inherited from application.Cell
void update ()
void setCurrentState (Color color)
void setXPos (int x)
void setYPos (int y)
void setGridEdgeType (String s)
void setGridLocationShape (String s)
Package Attributes inherited from application.Cell
int xPos
int yPos
Paint currentState
Paint updatedState
double threshold
String gridEdgeType
String gridLocationShape
Cell[][] Matrix
Map< Integer, Cell > neighbors = new HashMap<Integer, Cell>()
int cellID
Detailed Description
INCOMPLETE Date: 9/14/2014
Author
Michael Deng
Pranava Raparla
David Zhang
Definition at line 17 of file AntCell2.java.
Member Function Documentation
void application.AntCell2.antForage () private
Definition at line 51 of file AntCell2.java.
References application.Cell.currentState, application.AntCell2.goHome(), application.Cell.Matrix, application.Cell.xPos, and application.Cell.yPos.
void application.AntCell2.goHome (AntCell2 cell) private
Definition at line 62 of file AntCell2.java.
References application.homeMoveTo().
Referenced by application.AntCell2.antForage().
void application.AntCell2.updateCell (int i, int j, Cell cellMatrix[][]) protected
Definition at line 43 of file AntCell2.java.
References application.Cell.Matrix, application.Cell.xPos, and application.Cell.yPos.
Member Data Documentation
int application.AntCell2.foodPheromones private
Definition at line 23 of file AntCell2.java.
boolean application.AntCell2.hasFood = false private
Definition at line 20 of file AntCell2.java.
Referenced by application.dropHomePheromone(), and application.homeMoveTo().
int application.AntCell2.homePheromones private
Definition at line 22 of file AntCell2.java.
int application.AntCell2.largestPheromone private
Definition at line 26 of file AntCell2.java.
List<AntCell2> application.AntCell2.moveForwardList = new ArrayList<AntCell2>() private
Definition at line 28 of file AntCell2.java.
int application.AntCell2.newOrientation private
Definition at line 24 of file AntCell2.java.
int application.AntCell2.Orientation private
Definition at line 21 of file AntCell2.java.
Referenced by application.dropHomePheromone(), and application.homeMoveTo().
int application.AntCell2.pheromoneConstant = 3 private
Definition at line 25 of file AntCell2.java.
List<AntCell2> application.AntCell2.pheromoneList = new ArrayList<AntCell2>() private
Definition at line 29 of file AntCell2.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/AntCell2.java