cellsociety_team09: Package application
Package application
Classes
class AntCell
class AntCell2
class ApplicationConstants
class ApplicationLoop
class Cell
class CellXMLReader
class FireCell
class FireCellTester
class FloodCell
class GameOfLife
class GameOfLifeCell
class Grid
class Main
class Segregation
class SegregationCell
class WaTorCell
class WaTorCell2
class WaTorCell3
Functions
void homeMoveTo (AntCell2 cell)
void dropHomePheromone (AntCell2 cell)
Function Documentation
void application.dropHomePheromone (AntCell2 cell) private
Definition at line 81 of file AntCell2.java.
References application.AntCell2.hasFood, application.AntCell2.Orientation, application.Cell.xPos, and application.Cell.yPos.
Referenced by homeMoveTo().
void application.homeMoveTo (AntCell2 cell) private
Definition at line 72 of file AntCell2.java.
References dropHomePheromone(), application.AntCell2.hasFood, application.AntCell2.Orientation, and application.Cell.updatedState.
Referenced by application.AntCell2.goHome().