cellsociety_team09: application.GameOfLife Class Reference
application.GameOfLife Class Reference
Public Member Functions
void updateCell (int i, int j, Cell[][] cellMatrix)
Public Member Functions inherited from application.Cell
void setThreshold (double num)
String toString ()
Private Member Functions
int aliveCalculator ()
void lifeUpdate (int count)
Private Attributes
int Alive
Additional Inherited Members
Protected Member Functions inherited from application.Cell
abstract void updateCell (int i, int j, Cell[][] cellMatrix)
List findWantedNeighbors (Color color)
List findWantedNeighbors (Color currentColor, Color updatedColor)
List findWantedNeighbors (Cell otherCell, Color currentColor, Color updatedColor)
Package Functions inherited from application.Cell
void update ()
void setCurrentState (Color color)
void setXPos (int x)
void setYPos (int y)
void setGridEdgeType (String s)
void setGridLocationShape (String s)
Package Attributes inherited from application.Cell
int xPos
int yPos
Paint currentState
Paint updatedState
double threshold
String gridEdgeType
String gridLocationShape
Cell[][] Matrix
Map< Integer, Cell > neighbors = new HashMap<Integer, Cell>()
int cellID
Detailed Description
Definition at line 5 of file GameOfLife.java.
Member Function Documentation
int application.GameOfLife.aliveCalculator () private
Definition at line 22 of file GameOfLife.java.
References application.GameOfLife.Alive, application.Cell.currentState, application.Cell.Matrix, application.ApplicationConstants.NUM_OF_COLUMNS, application.ApplicationConstants.NUM_OF_ROWS, application.Cell.xPos, and application.Cell.yPos.
Referenced by application.GameOfLife.updateCell().
void application.GameOfLife.lifeUpdate (int count) private
Definition at line 41 of file GameOfLife.java.
References application.Cell.currentState, and application.Cell.updatedState.
Referenced by application.GameOfLife.updateCell().
void application.GameOfLife.updateCell (int i, int j, Cell cellMatrix[][])
Definition at line 10 of file GameOfLife.java.
References application.GameOfLife.aliveCalculator(), application.GameOfLife.lifeUpdate(), application.Cell.Matrix, application.Cell.xPos, and application.Cell.yPos.
Member Data Documentation
int application.GameOfLife.Alive private
Definition at line 7 of file GameOfLife.java.
Referenced by application.GameOfLife.aliveCalculator().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/GameOfLife.java