cellsociety_team09: application.Grid Class Reference
application.Grid Class Reference
Public Member Functions
void updateGrid (GridPane gridpane)
Grid (int row, int col)
void initializeAndPopulateMatrix (int i, int j, Paint initialColor, Cell cell)
void initializeAndPopulateMatrix (Cell cell)
void changeCellState (Node node)
void populateMatrixNeighborMaps (CellXMLReader cxr)
Package Functions
void setRoot (Group root)
Package Attributes
Cell[][] cellMatrix
Private Member Functions
void updateCellMatrix ()
void repopulateGridPane (GridPane gridpane)
Map createCornerNeighborsMap (int i, int j)
Map createCardinalNeighborsMap (int i, int j)
Map createSquareNeighborsMap (int i, int j)
Map createToroidalCornerNeighborsMap (int i, int j)
Map createToroidalCardinalNeighborsMap (int i, int j)
Map createToroidalSquareNeighborsMap (int i, int j)
Map createHexagonalNeighborsMap (int i, int j)
void addCellsToMap (int i, int j, int[] x, int[] y, Map map)
boolean checkBounds (int i, int j)
Private Attributes
Group root
int cellID = 0
Detailed Description
Version 1 Date: 9/14/2014
Author
Michael Deng
Pranava Raparla
David Zhang
Definition at line 27 of file Grid.java.
Constructor & Destructor Documentation
application.Grid.Grid (int row, int col)
Definition at line 43 of file Grid.java.
Member Function Documentation
void application.Grid.addCellsToMap (int i, int j, int[] x, int[] y, Map map) private
Adds cells to a map if not out of bounds
Parameters
i The x position of the particular cell
j The y position of the particular cell
x An array of x positions
y An array of y positions
map The map that needs to be added to
Definition at line 291 of file Grid.java.
References application.Grid.checkBounds().
Referenced by application.Grid.createCardinalNeighborsMap(), application.Grid.createCornerNeighborsMap(), and application.Grid.createHexagonalNeighborsMap().
void application.Grid.changeCellState (Node node)
Changes the cell state of a particular cell
Parameters
node The cell being referenced
Definition at line 125 of file Grid.java.
References application.ApplicationConstants.CELL_WIDTH, application.Cell.currentState, and application.Cell.updatedState.
Referenced by application.ApplicationLoop.editGrid().
boolean application.Grid.checkBounds (int i, int j) private
Checks to make sure referenced locations are in the bounds of the grid
Parameters
i The x position of the particular location
j The x position of the particular location
Returns
Definition at line 305 of file Grid.java.
Referenced by application.Grid.addCellsToMap(), application.Grid.createToroidalCardinalNeighborsMap(), and application.Grid.createToroidalCornerNeighborsMap().
Map application.Grid.createCardinalNeighborsMap (int i, int j) private
Creates a map of cardinal directional neighbors for a particular cell
Parameters
i The x position of the particular cell
j The y position of the particular cell
Returns
: The map of cardinal directional neighbors
Definition at line 159 of file Grid.java.
References application.Grid.addCellsToMap().
Referenced by application.Grid.createSquareNeighborsMap(), application.Grid.createToroidalCardinalNeighborsMap(), and application.Grid.populateMatrixNeighborMaps().
Map application.Grid.createCornerNeighborsMap (int i, int j) private
Creates a map of corner neighbors for a particular cell
Parameters
i The x position of the particular cell
j The y position of the particular cell
Returns
: The map of corner neighbors
Definition at line 145 of file Grid.java.
References application.Grid.addCellsToMap().
Referenced by application.Grid.createSquareNeighborsMap(), application.Grid.createToroidalCornerNeighborsMap(), and application.Grid.populateMatrixNeighborMaps().
Map application.Grid.createHexagonalNeighborsMap (int i, int j) private
Creates a map of neighbors based off of how hexagons link (non-toroidal)
Parameters
i The x position of the particular cell
j The y position of the particular cell
Returns
: The map of hexagonal neighbors
Definition at line 275 of file Grid.java.
References application.Grid.addCellsToMap().
Referenced by application.Grid.populateMatrixNeighborMaps().
Map application.Grid.createSquareNeighborsMap (int i, int j) private
Creates a map of square neighbors for a particular cell
Parameters
i The x position of the particular cell
j The y position of the particular cell
Returns
: The map of square neighbors
Definition at line 173 of file Grid.java.
References application.Grid.createCardinalNeighborsMap(), and application.Grid.createCornerNeighborsMap().
Referenced by application.Grid.populateMatrixNeighborMaps().
Map application.Grid.createToroidalCardinalNeighborsMap (int i, int j) private
Creates a map of cardinal directional neighbors for a particular cell with toroidal capabilities
Parameters
i The x position of the particular cell
j The y position of the particular cell
Returns
: The map of cardinal directional neighbors
Definition at line 240 of file Grid.java.
References application.Cell.cellID, application.Grid.checkBounds(), application.Grid.createCardinalNeighborsMap(), application.ApplicationConstants.NUM_OF_COLUMNS, and application.ApplicationConstants.NUM_OF_ROWS.
Referenced by application.Grid.createToroidalSquareNeighborsMap(), and application.Grid.populateMatrixNeighborMaps().
Map application.Grid.createToroidalCornerNeighborsMap (int i, int j) private
Creates a map of corner neighbors for a particular cell with toroidal capabilities
Parameters
i The x position of the particular cell
j The y position of the particular cell
Returns
: The map of corner neighbors
Definition at line 185 of file Grid.java.
References application.Cell.cellID, application.Grid.checkBounds(), application.Grid.createCornerNeighborsMap(), application.ApplicationConstants.NUM_OF_COLUMNS, and application.ApplicationConstants.NUM_OF_ROWS.
Referenced by application.Grid.createToroidalSquareNeighborsMap(), and application.Grid.populateMatrixNeighborMaps().
Map application.Grid.createToroidalSquareNeighborsMap (int i, int j) private
Creates a map of square neighbors for a particular cell with toroidal capabilities
Parameters
i The x position of the particular cell
j The y position of the particular cell
Returns
: The map of square neighbors
Definition at line 263 of file Grid.java.
References application.Grid.createToroidalCardinalNeighborsMap(), and application.Grid.createToroidalCornerNeighborsMap().
Referenced by application.Grid.populateMatrixNeighborMaps().
void application.Grid.initializeAndPopulateMatrix (int i, int j, Paint initialColor, Cell cell)
Populates the values in the individual cells in the cellMatrix
Parameters
i The x position of the cell
j The y position of the cell
initialColor The initial color of the cell Populates the values in the individual cells in the cellMatrix
i The x position of the cell
j The y position of the cell
initialColor The initial color of the cell
Definition at line 68 of file Grid.java.
References application.Grid.cellID, application.Cell.cellID, application.Cell.currentState, application.Cell.setXPos(), and application.Cell.setYPos().
Referenced by application.ApplicationLoop.initializeGridPane().
void application.Grid.initializeAndPopulateMatrix (Cell cell)
Populates the values in the individual cell of the cellMatrix
Parameters
cell The cell to populate the CellMatrix cell
Definition at line 81 of file Grid.java.
References application.Grid.cellID, application.Cell.cellID, application.Cell.xPos, and application.Cell.yPos.
void application.Grid.populateMatrixNeighborMaps (CellXMLReader cxr)
Populates the neighbors of each of the cells in the cell matrix
Definition at line 312 of file Grid.java.
References application.Grid.createCardinalNeighborsMap(), application.Grid.createCornerNeighborsMap(), application.Grid.createHexagonalNeighborsMap(), application.Grid.createSquareNeighborsMap(), application.Grid.createToroidalCardinalNeighborsMap(), application.Grid.createToroidalCornerNeighborsMap(), application.Grid.createToroidalSquareNeighborsMap(), application.CellXMLReader.getGridEdgeType(), application.CellXMLReader.getGridLocationShape(), application.CellXMLReader.getGridNeighborType(), application.Cell.neighbors, application.ApplicationConstants.NUM_OF_COLUMNS, and application.ApplicationConstants.NUM_OF_ROWS.
Referenced by application.ApplicationLoop.init().
void application.Grid.repopulateGridPane (GridPane gridpane) private
Repopulates the gridpane with the updatedCells from the cell Matrix
Parameters
gridpane The physical grid that displays on the application
Definition at line 102 of file Grid.java.
References application.Cell.currentState, application.ApplicationConstants.NUM_OF_COLUMNS, application.ApplicationConstants.NUM_OF_ROWS, and application.Cell.updatedState.
Referenced by application.Grid.updateGrid().
void application.Grid.setRoot (Group root) package
Grabs the root value from the application loop
Parameters
root The stack that holds a pages modules
Definition at line 117 of file Grid.java.
References application.Grid.root.
Referenced by application.ApplicationLoop.init().
void application.Grid.updateCellMatrix () private
Updates the states of the cells in the cell matrix
Definition at line 90 of file Grid.java.
References application.ApplicationConstants.NUM_OF_COLUMNS, application.ApplicationConstants.NUM_OF_ROWS, and application.Cell.updateCell().
Referenced by application.Grid.updateGrid().
void application.Grid.updateGrid (GridPane gridpane)
Updates the cell matrix and the gridpane
Parameters
gridpane The physical grid that displays on the application
Definition at line 38 of file Grid.java.
References application.Grid.repopulateGridPane(), and application.Grid.updateCellMatrix().
Referenced by application.ApplicationLoop.updateGameLoop().
Member Data Documentation
int application.Grid.cellID = 0 private
Definition at line 32 of file Grid.java.
Referenced by application.Grid.initializeAndPopulateMatrix().
Cell [][] application.Grid.cellMatrix package
Definition at line 30 of file Grid.java.
Referenced by application.ApplicationLoop.initializeGridPane().
Group application.Grid.root private
Definition at line 31 of file Grid.java.
Referenced by application.Grid.setRoot().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/Grid.java