cellsociety_team09: application.Segregation Class Reference
application.Segregation Class Reference
Public Member Functions
Segregation ()
void setThreshold (double num)
void updateCell (int i, int j, Cell[][] cellMatrix)
Public Member Functions inherited from application.Cell
void setThreshold (double num)
String toString ()
Public Attributes
double threshold
Protected Member Functions
void updateCell (int i, int j)
Protected Member Functions inherited from application.Cell
abstract void updateCell (int i, int j, Cell[][] cellMatrix)
List findWantedNeighbors (Color color)
List findWantedNeighbors (Color currentColor, Color updatedColor)
List findWantedNeighbors (Cell otherCell, Color currentColor, Color updatedColor)
Private Member Functions
double percentageCalc ()
void cellMover (double percentage)
Private Attributes
double same = 0
double different = 0
Additional Inherited Members
Package Functions inherited from application.Cell
void update ()
void setCurrentState (Color color)
void setXPos (int x)
void setYPos (int y)
void setGridEdgeType (String s)
void setGridLocationShape (String s)
Package Attributes inherited from application.Cell
int xPos
int yPos
Paint currentState
Paint updatedState
double threshold
String gridEdgeType
String gridLocationShape
Cell[][] Matrix
Map< Integer, Cell > neighbors = new HashMap<Integer, Cell>()
int cellID
Detailed Description
Definition at line 6 of file Segregation.java.
Constructor & Destructor Documentation
application.Segregation.Segregation ()
Definition at line 12 of file Segregation.java.
References application.Cell.xPos.
Member Function Documentation
void application.Segregation.cellMover (double percentage) private
Definition at line 54 of file Segregation.java.
References application.Cell.currentState, application.Cell.Matrix, application.ApplicationConstants.NUM_OF_COLUMNS, application.ApplicationConstants.NUM_OF_ROWS, application.Cell.updatedState, application.Cell.xPos, and application.Cell.yPos.
Referenced by application.Segregation.updateCell().
double application.Segregation.percentageCalc () private
Definition at line 28 of file Segregation.java.
References application.Cell.currentState, application.Segregation.different, application.Cell.Matrix, application.ApplicationConstants.NUM_OF_COLUMNS, application.ApplicationConstants.NUM_OF_ROWS, application.Cell.xPos, and application.Cell.yPos.
Referenced by application.Segregation.updateCell().
void application.Segregation.setThreshold (double num)
Definition at line 20 of file Segregation.java.
void application.Segregation.updateCell (int i, int j, Cell cellMatrix[][])
Definition at line 74 of file Segregation.java.
References application.Segregation.cellMover(), application.Segregation.percentageCalc(), application.Cell.xPos, and application.Cell.yPos.
void application.Segregation.updateCell (int i, int j) protected
Definition at line 86 of file Segregation.java.
Member Data Documentation
double application.Segregation.different = 0 private
Definition at line 9 of file Segregation.java.
Referenced by application.Segregation.percentageCalc().
double application.Segregation.same = 0 private
Definition at line 8 of file Segregation.java.
double application.Segregation.threshold
Definition at line 10 of file Segregation.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/Segregation.java