cellsociety_team09: application.ApplicationLoop Class Reference
application.ApplicationLoop Class Reference
Public Member Functions
Scene init (Stage s, Integer width, Integer height, CellXMLReader cxr)
KeyFrame start (Double frameRate)
void updateGameLoop ()
Group getRoot ()
void populateLineChart (LineChart lineChart)
Public Attributes
boolean goToErrorPage = false
Package Attributes
ArrayList< XYChart.Series > series
Private Member Functions
GridPane initializeGridPane (Group root)
Paint generateRandomColor ()
Polygon generateRect ()
Polygon generateRect (Paint color)
Polygon generateRectHelper (Paint color)
Polygon generateHex ()
Polygon generateHex (Paint color)
Polygon generateHexHelper (Paint color)
void addPointsToLineChart (int index, int XValue, int YValue)
Integer countNumberOfCertainColorSpaces (Color color)
void editGrid (ObservableList< Node > list)
Private Attributes
GridPane gridpane
Grid grid
Group root
CellXMLReader cellXMLReader
Timeline animation
int currentFrameCount
EventHandler< ActionEvent > oneFrame
Detailed Description
Version 1 Date: 9/14/2014
Author
Michael Deng
Pranava Raparla
David Zhang
Definition at line 45 of file ApplicationLoop.java.
Member Function Documentation
void application.ApplicationLoop.addPointsToLineChart (int index, int XValue, int YValue) private
Adds points to the lineChart once per frame
Parameters
XValue The current frame
YValue The number of a certain type of blocks
Definition at line 305 of file ApplicationLoop.java.
References application.ApplicationLoop.series.
Referenced by application.ApplicationLoop.updateGameLoop().
Integer application.ApplicationLoop.countNumberOfCertainColorSpaces (Color color) private
Counts the number of blocks of a specified color in the grid
Parameters
color The specified color the program wants to check
Returns
: The number of certain colored blocks
Definition at line 315 of file ApplicationLoop.java.
Referenced by application.ApplicationLoop.updateGameLoop().
void application.ApplicationLoop.editGrid (ObservableList< Node > list) private
Allows the grid to be editable when the game is paused
Definition at line 328 of file ApplicationLoop.java.
References application.ApplicationConstants.CELL_WIDTH, application.Grid.changeCellState(), application.ApplicationConstants.gridEditable, and application.ApplicationConstants.NUM_OF_ROWS.
Referenced by application.ApplicationLoop.init().
Polygon application.ApplicationLoop.generateHex () private
Generates a cell in the form of a hexagon with random color
Returns
: The newly created rectangle for the grid pane
Definition at line 200 of file ApplicationLoop.java.
References application.ApplicationLoop.generateHexHelper(), and application.ApplicationLoop.generateRandomColor().
Polygon application.ApplicationLoop.generateHex (Paint color) private
Generates a cell in the form of a hexagon
Parameters
color The color of the cell
Returns
: The newly created rectangle for the grid pane
Definition at line 209 of file ApplicationLoop.java.
References application.ApplicationLoop.generateHexHelper().
Polygon application.ApplicationLoop.generateHexHelper (Paint color) private
Helper method for generating a cell in the form of a hexagon
Parameters
color The color of the cell
Returns
: The newly created rectangle for the gird pane
Definition at line 218 of file ApplicationLoop.java.
References application.ApplicationConstants.CELL_WIDTH.
Referenced by application.ApplicationLoop.generateHex().
Paint application.ApplicationLoop.generateRandomColor () private
Returns
Definition at line 148 of file ApplicationLoop.java.
References application.CellXMLReader.myColors.
Referenced by application.ApplicationLoop.generateHex(), and application.ApplicationLoop.generateRect().
Polygon application.ApplicationLoop.generateRect () private
Generates a cell in the form of a rectangle with random color
Returns
: The newly created rectangle for the grid pane
Definition at line 166 of file ApplicationLoop.java.
References application.ApplicationLoop.generateRandomColor(), and application.ApplicationLoop.generateRectHelper().
Referenced by application.ApplicationLoop.initializeGridPane().
Polygon application.ApplicationLoop.generateRect (Paint color) private
Generates a cell in the form of a rectangle
Parameters
color The color of the cell
Returns
: The newly created rectangle for the grid pane
Definition at line 175 of file ApplicationLoop.java.
References application.ApplicationLoop.generateRectHelper().
Polygon application.ApplicationLoop.generateRectHelper (Paint color) private
Helper method for generating Rect of certain color
Parameters
color The color of the cell
Returns
: The newly created rectangle for the grid pane
Definition at line 184 of file ApplicationLoop.java.
References application.ApplicationConstants.CELL_WIDTH.
Referenced by application.ApplicationLoop.generateRect().
Group application.ApplicationLoop.getRoot ()
Gets the root of the current scene
Returns
: The root of the main game's scene
Definition at line 282 of file ApplicationLoop.java.
References application.ApplicationLoop.root.
Referenced by application.Main.playGame().
Scene application.ApplicationLoop.init (Stage s, Integer width, Integer height, CellXMLReader cxr)
Creates the group and the scene for the main game play
Parameters
s : The application stage
width : The pixel width of the application
height : The pixel height of the application
Returns
: Returns the scene in which the game occurs
Definition at line 80 of file ApplicationLoop.java.
References application.ApplicationLoop.editGrid(), application.ApplicationLoop.initializeGridPane(), application.CellXMLReader.myCols, application.CellXMLReader.myRows, application.Grid.populateMatrixNeighborMaps(), and application.Grid.setRoot().
Referenced by application.Main.playGame().
GridPane application.ApplicationLoop.initializeGridPane (Group root) private
Creates what the initial GridPane and cellMatrix look li)ke
Parameters
root The stack all the modules of the page go on
Returns
: The newly created GirdPane
Definition at line 115 of file ApplicationLoop.java.
References application.Grid.cellMatrix, application.CellXMLReader.checkModelTypeAndInitializeCell(), application.Cell.currentState, application.ApplicationLoop.generateRect(), application.CellXMLReader.getCellList(), application.Grid.initializeAndPopulateMatrix(), application.CellXMLReader.myColors, application.CellXMLReader.myModelType, application.ApplicationConstants.NUM_OF_COLUMNS, application.ApplicationConstants.NUM_OF_ROWS, and application.Cell.yPos.
Referenced by application.ApplicationLoop.init().
void application.ApplicationLoop.populateLineChart (LineChart lineChart)
Gives the linechart the capacity to have data inputted
Parameters
lineChart The physical graph
Definition at line 290 of file ApplicationLoop.java.
References application.CellXMLReader.myColors, and application.ApplicationLoop.series.
Referenced by application.Main.createGameGraph().
KeyFrame application.ApplicationLoop.start (Double frameRate)
Create the game's frame
Definition at line 96 of file ApplicationLoop.java.
References application.ApplicationLoop.oneFrame.
Referenced by application.Main.runGameLoop().
void application.ApplicationLoop.updateGameLoop ()
Updates the grid
Definition at line 103 of file ApplicationLoop.java.
References application.ApplicationLoop.addPointsToLineChart(), application.ApplicationLoop.countNumberOfCertainColorSpaces(), application.CellXMLReader.myColors, and application.Grid.updateGrid().
Referenced by application.Main.activateStepThroughFrame().
Member Data Documentation
Timeline application.ApplicationLoop.animation private
Definition at line 51 of file ApplicationLoop.java.
CellXMLReader application.ApplicationLoop.cellXMLReader private
Definition at line 50 of file ApplicationLoop.java.
int application.ApplicationLoop.currentFrameCount private
Definition at line 56 of file ApplicationLoop.java.
boolean application.ApplicationLoop.goToErrorPage = false
Definition at line 55 of file ApplicationLoop.java.
Grid application.ApplicationLoop.grid private
Definition at line 48 of file ApplicationLoop.java.
GridPane application.ApplicationLoop.gridpane private
Definition at line 47 of file ApplicationLoop.java.
EventHandler<ActionEvent> application.ApplicationLoop.oneFrame private
Initial value:
= new EventHandler<ActionEvent>() {
        @Override
        public void handle(ActionEvent evt) {
            updateGameLoop();
        }
    }
Function to do each game frame
Definition at line 62 of file ApplicationLoop.java.
Referenced by application.ApplicationLoop.start().
Group application.ApplicationLoop.root private
Definition at line 49 of file ApplicationLoop.java.
Referenced by application.ApplicationLoop.getRoot().
ArrayList<XYChart.Series> application.ApplicationLoop.series package
Definition at line 53 of file ApplicationLoop.java.
Referenced by application.ApplicationLoop.addPointsToLineChart(), and application.ApplicationLoop.populateLineChart().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/ApplicationLoop.java