cellsociety_team09: application.AntCell Class Reference
application.AntCell Class Reference
Protected Member Functions
void updateCell (int i, int j, Cell[][] cellMatrix)
Protected Member Functions inherited from application.Cell
abstract void updateCell (int i, int j, Cell[][] cellMatrix)
List findWantedNeighbors (Color color)
List findWantedNeighbors (Color currentColor, Color updatedColor)
List findWantedNeighbors (Cell otherCell, Color currentColor, Color updatedColor)
Private Member Functions
void antForage ()
void goHome (AntCell cell)
void homeMoveTo (AntCell cell)
void dropHomePheromone (AntCell cell)
void pheromoneNeighbourFinder (AntCell cell)
void findLargestHomePheromone (List list)
void findLargestFoodPheromone (List list)
void checkForwardHome (AntCell cell)
void checkForwardFood (AntCell cell)
AntCell findLargestHome (AntCell cell1, AntCell cell2, AntCell cell3)
AntCell findLargestFood (AntCell cell1, AntCell cell2, AntCell cell3)
void newOrientationFinder (AntCell cell)
boolean checkBounds (int i, int j)
Private Attributes
boolean hasFood = false
int Orientation
int homePheromones
int foodPheromones
int newOrientation
int pheromoneConstant = 3
int largestPheromone
List< AntCell > moveForwardList = new ArrayList<AntCell>()
List< AntCell > pheromoneList = new ArrayList<AntCell>()
Additional Inherited Members
Public Member Functions inherited from application.Cell
void setThreshold (double num)
String toString ()
Package Functions inherited from application.Cell
void update ()
void setCurrentState (Color color)
void setXPos (int x)
void setYPos (int y)
void setGridEdgeType (String s)
void setGridLocationShape (String s)
Package Attributes inherited from application.Cell
int xPos
int yPos
Paint currentState
Paint updatedState
double threshold
String gridEdgeType
String gridLocationShape
Cell[][] Matrix
Map< Integer, Cell > neighbors = new HashMap<Integer, Cell>()
int cellID
Detailed Description
Version 1
INCOMPLETE
Date: 9/14/2014
Author
Michael Deng
Pranava Raparla
David Zhang
Definition at line 21 of file AntCell.java.
Member Function Documentation
void application.AntCell.antForage () private
Definition at line 55 of file AntCell.java.
References application.Cell.currentState, application.AntCell.goHome(), application.Cell.Matrix, application.Cell.xPos, and application.Cell.yPos.
boolean application.AntCell.checkBounds (int i, int j) private
Definition at line 231 of file AntCell.java.
Referenced by application.AntCell.findLargestFood(), application.AntCell.findLargestHome(), and application.AntCell.pheromoneNeighbourFinder().
void application.AntCell.checkForwardFood (AntCell cell) private
Definition at line 139 of file AntCell.java.
References application.AntCell.findLargestFood(), application.Cell.Matrix, application.AntCell.Orientation, application.Cell.xPos, and application.Cell.yPos.
void application.AntCell.checkForwardHome (AntCell cell) private
Definition at line 117 of file AntCell.java.
References application.AntCell.findLargestHome(), application.Cell.Matrix, application.AntCell.Orientation, application.Cell.xPos, and application.Cell.yPos.
void application.AntCell.dropHomePheromone (AntCell cell) private
Definition at line 81 of file AntCell.java.
References application.AntCell.pheromoneConstant.
Referenced by application.AntCell.homeMoveTo().
AntCell application.AntCell.findLargestFood (AntCell cell1, AntCell cell2, AntCell cell3) private
Definition at line 184 of file AntCell.java.
References application.AntCell.checkBounds(), application.Cell.xPos, and application.Cell.yPos.
Referenced by application.AntCell.checkForwardFood().
void application.AntCell.findLargestFoodPheromone (List list) private
Definition at line 111 of file AntCell.java.
Referenced by application.AntCell.pheromoneNeighbourFinder().
AntCell application.AntCell.findLargestHome (AntCell cell1, AntCell cell2, AntCell cell3) private
Definition at line 162 of file AntCell.java.
References application.AntCell.checkBounds(), application.Cell.xPos, and application.Cell.yPos.
Referenced by application.AntCell.checkForwardHome().
void application.AntCell.findLargestHomePheromone (List list) private
Definition at line 107 of file AntCell.java.
Referenced by application.AntCell.pheromoneNeighbourFinder().
void application.AntCell.goHome (AntCell cell) private
Definition at line 66 of file AntCell.java.
Referenced by application.AntCell.antForage().
void application.AntCell.homeMoveTo (AntCell cell) private
Definition at line 72 of file AntCell.java.
References application.AntCell.dropHomePheromone(), application.AntCell.hasFood, application.Cell.Matrix, application.AntCell.newOrientation, application.AntCell.Orientation, application.Cell.updatedState, application.Cell.xPos, and application.Cell.yPos.
void application.AntCell.newOrientationFinder (AntCell cell) private
Definition at line 208 of file AntCell.java.
References application.Cell.Matrix, application.Cell.xPos, and application.Cell.yPos.
void application.AntCell.pheromoneNeighbourFinder (AntCell cell) private
Definition at line 87 of file AntCell.java.
References application.AntCell.checkBounds(), application.AntCell.findLargestFoodPheromone(), application.AntCell.findLargestHomePheromone(), application.AntCell.hasFood, application.Cell.Matrix, application.Cell.xPos, and application.Cell.yPos.
void application.AntCell.updateCell (int i, int j, Cell cellMatrix[][]) protected
Definition at line 47 of file AntCell.java.
References application.Cell.Matrix, application.Cell.xPos, and application.Cell.yPos.
Member Data Documentation
int application.AntCell.foodPheromones private
Definition at line 27 of file AntCell.java.
boolean application.AntCell.hasFood = false private
Definition at line 24 of file AntCell.java.
Referenced by application.AntCell.homeMoveTo(), and application.AntCell.pheromoneNeighbourFinder().
int application.AntCell.homePheromones private
Definition at line 26 of file AntCell.java.
int application.AntCell.largestPheromone private
Definition at line 30 of file AntCell.java.
List<AntCell> application.AntCell.moveForwardList = new ArrayList<AntCell>() private
Definition at line 32 of file AntCell.java.
int application.AntCell.newOrientation private
Definition at line 28 of file AntCell.java.
Referenced by application.AntCell.homeMoveTo().
int application.AntCell.Orientation private
Definition at line 25 of file AntCell.java.
Referenced by application.AntCell.checkForwardFood(), application.AntCell.checkForwardHome(), and application.AntCell.homeMoveTo().
int application.AntCell.pheromoneConstant = 3 private
Definition at line 29 of file AntCell.java.
Referenced by application.AntCell.dropHomePheromone().
List<AntCell> application.AntCell.pheromoneList = new ArrayList<AntCell>() private
Definition at line 33 of file AntCell.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/AntCell.java