cellsociety_team09: application.CellXMLReader Class Reference
application.CellXMLReader Class Reference
Public Member Functions
CellXMLReader ()
Document getDocument ()
List< Cell > getCellList ()
String getModelType ()
ArrayList< Color > getAvailableColors ()
String getGridLocationShape ()
String getGridEdgeType ()
String getGridNeighborType ()
void loadAndParseXMLFile (String filename) throws ParserConfigurationException, IOException, SAXException
void populateCellListFromDocument ()
void configureModelParameters (Element modelParameters)
void setColorScheme (String s)
void setWaTorVariables (Element watorModelParameters)
Cell checkModelTypeAndInitializeCell ()
void loadAttributesIntoCell (String statesToParse)
void printCellList (List< Cell > cellList)
Public Attributes
Document myDocument
NodeList myNodeList
List< Cell > myCellList
String myModelType
double myThreshold
String myGridEdgeType
String myGridLocationShape
String myGridNeighborType
ArrayList< Color > myColors
ArrayList< Integer > myWaTorVariables
int myRows
int myCols
Detailed Description
Definition at line 14 of file CellXMLReader.java.
Constructor & Destructor Documentation
application.CellXMLReader.CellXMLReader ()
Definition at line 32 of file CellXMLReader.java.
Member Function Documentation
Cell application.CellXMLReader.checkModelTypeAndInitializeCell ()
Returns
Definition at line 209 of file CellXMLReader.java.
Referenced by application.ApplicationLoop.initializeGridPane(), and application.CellXMLReader.loadAttributesIntoCell().
void application.CellXMLReader.configureModelParameters (Element modelParameters)
Parameters
modelParameters
Definition at line 152 of file CellXMLReader.java.
References application.CellXMLReader.setColorScheme(), and application.CellXMLReader.setWaTorVariables().
Referenced by application.CellXMLReader.populateCellListFromDocument().
ArrayList<Color> application.CellXMLReader.getAvailableColors ()
Returns
Definition at line 68 of file CellXMLReader.java.
References application.CellXMLReader.myColors.
List<Cell> application.CellXMLReader.getCellList ()
Returns
Definition at line 52 of file CellXMLReader.java.
References application.CellXMLReader.myCellList.
Referenced by application.ApplicationLoop.initializeGridPane().
Document application.CellXMLReader.getDocument ()
Returns
Definition at line 44 of file CellXMLReader.java.
References application.CellXMLReader.myDocument.
String application.CellXMLReader.getGridEdgeType ()
Returns
Definition at line 83 of file CellXMLReader.java.
References application.CellXMLReader.myGridEdgeType.
Referenced by application.Grid.populateMatrixNeighborMaps().
String application.CellXMLReader.getGridLocationShape ()
Returns
Definition at line 75 of file CellXMLReader.java.
References application.CellXMLReader.myGridLocationShape.
Referenced by application.Grid.populateMatrixNeighborMaps().
String application.CellXMLReader.getGridNeighborType ()
Returns
Definition at line 91 of file CellXMLReader.java.
References application.CellXMLReader.myGridNeighborType.
Referenced by application.Grid.populateMatrixNeighborMaps().
String application.CellXMLReader.getModelType ()
Returns
Definition at line 60 of file CellXMLReader.java.
References application.CellXMLReader.myModelType.
void application.CellXMLReader.loadAndParseXMLFile (String filename) throws ParserConfigurationException, IOException, SAXException
Parameters
filename
Exceptions
ParserConfigurationException
IOException
SAXException
Definition at line 102 of file CellXMLReader.java.
Referenced by application.Main.activateImportXMLButton().
void application.CellXMLReader.loadAttributesIntoCell (String statesToParse)
Parameters
element
Definition at line 237 of file CellXMLReader.java.
References application.CellXMLReader.checkModelTypeAndInitializeCell(), application.Cell.setCurrentState(), application.Cell.setThreshold(), application.Cell.setXPos(), and application.Cell.setYPos().
Referenced by application.CellXMLReader.populateCellListFromDocument().
void application.CellXMLReader.populateCellListFromDocument ()
Definition at line 114 of file CellXMLReader.java.
References application.CellXMLReader.configureModelParameters(), application.CellXMLReader.loadAttributesIntoCell(), and application.CellXMLReader.printCellList().
Referenced by application.Main.activateImportXMLButton().
void application.CellXMLReader.printCellList (List< Cell > cellList)
Parameters
cellList
Definition at line 261 of file CellXMLReader.java.
Referenced by application.CellXMLReader.populateCellListFromDocument().
void application.CellXMLReader.setColorScheme (String s)
Parameters
s
Definition at line 170 of file CellXMLReader.java.
Referenced by application.CellXMLReader.configureModelParameters().
void application.CellXMLReader.setWaTorVariables (Element watorModelParameters)
Definition at line 197 of file CellXMLReader.java.
Referenced by application.CellXMLReader.configureModelParameters().
Member Data Documentation
List<Cell> application.CellXMLReader.myCellList
Definition at line 18 of file CellXMLReader.java.
Referenced by application.CellXMLReader.getCellList().
ArrayList<Color> application.CellXMLReader.myColors
Definition at line 24 of file CellXMLReader.java.
Referenced by application.ApplicationLoop.generateRandomColor(), application.CellXMLReader.getAvailableColors(), application.ApplicationLoop.initializeGridPane(), application.ApplicationLoop.populateLineChart(), and application.ApplicationLoop.updateGameLoop().
int application.CellXMLReader.myCols
Definition at line 27 of file CellXMLReader.java.
Referenced by application.ApplicationLoop.init().
Document application.CellXMLReader.myDocument
Definition at line 16 of file CellXMLReader.java.
Referenced by application.CellXMLReader.getDocument().
String application.CellXMLReader.myGridEdgeType
Definition at line 21 of file CellXMLReader.java.
Referenced by application.CellXMLReader.getGridEdgeType().
String application.CellXMLReader.myGridLocationShape
Definition at line 22 of file CellXMLReader.java.
Referenced by application.CellXMLReader.getGridLocationShape().
String application.CellXMLReader.myGridNeighborType
Definition at line 23 of file CellXMLReader.java.
Referenced by application.CellXMLReader.getGridNeighborType().
String application.CellXMLReader.myModelType
Definition at line 19 of file CellXMLReader.java.
Referenced by application.CellXMLReader.getModelType(), and application.ApplicationLoop.initializeGridPane().
NodeList application.CellXMLReader.myNodeList
Definition at line 17 of file CellXMLReader.java.
int application.CellXMLReader.myRows
Definition at line 26 of file CellXMLReader.java.
Referenced by application.ApplicationLoop.init().
double application.CellXMLReader.myThreshold
Definition at line 20 of file CellXMLReader.java.
ArrayList<Integer> application.CellXMLReader.myWaTorVariables
Definition at line 25 of file CellXMLReader.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/CellXMLReader.java