cellsociety_team09: application.WaTorCell3 Class Reference
application.WaTorCell3 Class Reference
Public Member Functions
void updateCell (int i, int j, Cell[][] cellMatrix)
Public Member Functions inherited from application.Cell
void setThreshold (double num)
String toString ()
Package Functions
void setCurrentState (String s)
Package Functions inherited from application.Cell
void update ()
void setCurrentState (Color color)
void setXPos (int x)
void setYPos (int y)
void setGridEdgeType (String s)
void setGridLocationShape (String s)
Private Member Functions
void updateThisCell ()
void sharkUpdate ()
void fishUpdate ()
void eatFish ()
void moveShark ()
void moveFish ()
void sharkCheck (WaTorCell3 cell)
void fishCheck (WaTorCell3 cell)
void killShark (WaTorCell3 cell)
void breed (WaTorCell3 cell, Color color)
int randomFinder (List< WaTorCell3 > list)
Private Attributes
int fishTillBreed =3
int sharkTillDeath =6
int sharkTillBreed =6
int fishBreed = fishTillBreed
int sharkDeath = sharkTillDeath
int sharkBreed = sharkTillBreed
List< WaTorCell3 > moveFishList = new ArrayList<WaTorCell3>()
List< WaTorCell3 > eatFishList = new ArrayList<WaTorCell3>()
List< WaTorCell3 > moveSharkList = new ArrayList<WaTorCell3>()
List< WaTorCell3 > breedList = new ArrayList<WaTorCell3>()
Additional Inherited Members
Protected Member Functions inherited from application.Cell
abstract void updateCell (int i, int j, Cell[][] cellMatrix)
List findWantedNeighbors (Color color)
List findWantedNeighbors (Color currentColor, Color updatedColor)
List findWantedNeighbors (Cell otherCell, Color currentColor, Color updatedColor)
Package Attributes inherited from application.Cell
int xPos
int yPos
Paint currentState
Paint updatedState
double threshold
String gridEdgeType
String gridLocationShape
Cell[][] Matrix
Map< Integer, Cell > neighbors = new HashMap<Integer, Cell>()
int cellID
Detailed Description
Definition at line 9 of file WaTorCell3.java.
Member Function Documentation
void application.WaTorCell3.breed (WaTorCell3 cell, Color color) private
Definition at line 147 of file WaTorCell3.java.
References application.WaTorCell3.fishBreed, application.WaTorCell3.fishTillBreed, application.WaTorCell3.randomFinder(), application.WaTorCell3.sharkBreed, application.WaTorCell3.sharkTillBreed, application.WaTorCell3.sharkTillDeath, application.Cell.updatedState, application.Cell.xPos, and application.Cell.yPos.
Referenced by application.WaTorCell3.fishCheck(), and application.WaTorCell3.sharkCheck().
void application.WaTorCell3.eatFish () private
Definition at line 70 of file WaTorCell3.java.
References application.Cell.currentState, application.WaTorCell3.sharkCheck(), application.WaTorCell3.sharkTillDeath, and application.Cell.updatedState.
Referenced by application.WaTorCell3.sharkUpdate().
void application.WaTorCell3.fishCheck (WaTorCell3 cell) private
Definition at line 135 of file WaTorCell3.java.
References application.WaTorCell3.breed().
Referenced by application.WaTorCell3.moveFish().
void application.WaTorCell3.fishUpdate () private
Definition at line 64 of file WaTorCell3.java.
References application.WaTorCell3.moveFish().
Referenced by application.WaTorCell3.updateThisCell().
void application.WaTorCell3.killShark (WaTorCell3 cell) private
Definition at line 141 of file WaTorCell3.java.
References application.WaTorCell3.sharkBreed, application.WaTorCell3.sharkDeath, application.WaTorCell3.sharkTillBreed, application.WaTorCell3.sharkTillDeath, and application.Cell.updatedState.
Referenced by application.WaTorCell3.sharkCheck().
void application.WaTorCell3.moveFish () private
Definition at line 103 of file WaTorCell3.java.
References application.WaTorCell3.fishBreed, application.WaTorCell3.fishCheck(), application.Cell.Matrix, application.WaTorCell3.randomFinder(), application.Cell.updatedState, application.Cell.xPos, and application.Cell.yPos.
Referenced by application.WaTorCell3.fishUpdate().
void application.WaTorCell3.moveShark () private
Definition at line 80 of file WaTorCell3.java.
References application.Cell.Matrix, application.WaTorCell3.randomFinder(), application.WaTorCell3.sharkBreed, application.WaTorCell3.sharkCheck(), application.WaTorCell3.sharkDeath, application.Cell.updatedState, application.Cell.xPos, and application.Cell.yPos.
Referenced by application.WaTorCell3.sharkUpdate().
int application.WaTorCell3.randomFinder (List< WaTorCell3 > list) private
Definition at line 161 of file WaTorCell3.java.
References application.ApplicationConstants.rand.
Referenced by application.WaTorCell3.breed(), application.WaTorCell3.moveFish(), and application.WaTorCell3.moveShark().
void application.WaTorCell3.setCurrentState (String s) package
Definition at line 198 of file WaTorCell3.java.
void application.WaTorCell3.sharkCheck (WaTorCell3 cell) private
Definition at line 125 of file WaTorCell3.java.
References application.WaTorCell3.breed(), and application.WaTorCell3.killShark().
Referenced by application.WaTorCell3.eatFish(), and application.WaTorCell3.moveShark().
void application.WaTorCell3.sharkUpdate () private
Definition at line 53 of file WaTorCell3.java.
References application.WaTorCell3.eatFish(), application.WaTorCell3.moveShark(), application.Cell.xPos, and application.Cell.yPos.
Referenced by application.WaTorCell3.updateThisCell().
void application.WaTorCell3.updateCell (int i, int j, Cell cellMatrix[][])
Definition at line 34 of file WaTorCell3.java.
References application.Cell.Matrix, application.Cell.updatedState, application.WaTorCell3.updateThisCell(), application.Cell.xPos, and application.Cell.yPos.
void application.WaTorCell3.updateThisCell () private
Definition at line 43 of file WaTorCell3.java.
References application.Cell.currentState, application.WaTorCell3.fishUpdate(), application.WaTorCell3.sharkUpdate(), and application.Cell.updatedState.
Referenced by application.WaTorCell3.updateCell().
Member Data Documentation
List<WaTorCell3> application.WaTorCell3.breedList = new ArrayList<WaTorCell3>() private
Definition at line 25 of file WaTorCell3.java.
List<WaTorCell3> application.WaTorCell3.eatFishList = new ArrayList<WaTorCell3>() private
Definition at line 22 of file WaTorCell3.java.
int application.WaTorCell3.fishBreed = fishTillBreed private
Definition at line 16 of file WaTorCell3.java.
Referenced by application.WaTorCell3.breed(), and application.WaTorCell3.moveFish().
int application.WaTorCell3.fishTillBreed =3 private
Definition at line 12 of file WaTorCell3.java.
Referenced by application.WaTorCell3.breed().
List<WaTorCell3> application.WaTorCell3.moveFishList = new ArrayList<WaTorCell3>() private
Definition at line 20 of file WaTorCell3.java.
List<WaTorCell3> application.WaTorCell3.moveSharkList = new ArrayList<WaTorCell3>() private
Definition at line 23 of file WaTorCell3.java.
int application.WaTorCell3.sharkBreed = sharkTillBreed private
Definition at line 18 of file WaTorCell3.java.
Referenced by application.WaTorCell3.breed(), application.WaTorCell3.killShark(), and application.WaTorCell3.moveShark().
int application.WaTorCell3.sharkDeath = sharkTillDeath private
Definition at line 17 of file WaTorCell3.java.
Referenced by application.WaTorCell3.killShark(), and application.WaTorCell3.moveShark().
int application.WaTorCell3.sharkTillBreed =6 private
Definition at line 14 of file WaTorCell3.java.
Referenced by application.WaTorCell3.breed(), and application.WaTorCell3.killShark().
int application.WaTorCell3.sharkTillDeath =6 private
Definition at line 13 of file WaTorCell3.java.
Referenced by application.WaTorCell3.breed(), application.WaTorCell3.eatFish(), and application.WaTorCell3.killShark().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/WaTorCell3.java