cellsociety_team09: application.Main Class Reference
application.Main Class Reference
Public Member Functions
void start (Stage primaryStage)
void activateStartButton (Button btn, Stage stage)
void activateExitAppButton (Button btn)
void activateImportXMLButton (Button btn)
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void playGame (Stage stage)
void runGameLoop (Double speed)
void activateErrorPage ()
void populateStage (Stage stage, Scene scene)
void populateStartPageModules (Group root)
void populateGridPageModules (Group root)
void populateErrorPageModules (Group root)
Button createButton (String content, int x_Coord, int y_Coord, Group root)
Slider createSlider (int minValue, int maxValue, int x_Coord, int y_Coord, Group root)
Label createLabel (String content, int font_size, int x_Coord, int y_Coord, Group root)
LineChart createLineChart (String title, int x_Coord, int y_Coord, Group root)
void createStartGameButton (Group root)
void createExitButton (Group root)
void createImportXMLButton (Group root)
void createReturnToStartButton (Group root)
void createPauseButton (Group root)
void createResumeButton (Group root)
void createStepThroughButton (Group root)
void createSliderLabel (Group root)
void createSlider (Group root)
void createErrorMessage (Group root)
void createNameLabel (Group root)
void createTitleLabel (Group root)
void createGameGraph (Group root)
void setSliderEventListener (Slider slider)
void activatePauseAnimationButton (Button btn)
void activateResumeAnimationButton (Button btn)
void activateReturntoStart (Button btn)
void activateStepThroughFrame (Button btn)
Private Attributes
ApplicationLoop myGame
Stage primaryStage
Timeline animation
CellXMLReader cellXMLReader
Detailed Description
Version 1 Complete Date: 9/14/2014
Author
Michael Deng
Pranava Raparla
David Zhang
Definition at line 34 of file Main.java.
Member Function Documentation
void application.Main.activateErrorPage () private
Moves the application to the error page
Definition at line 84 of file Main.java.
References application.Main.populateErrorPageModules(), application.Main.populateStage(), application.ApplicationConstants.STAGE_HEIGHT, and application.ApplicationConstants.STAGE_WIDTH.
Referenced by application.Main.activateImportXMLButton().
void application.Main.activateExitAppButton (Button btn)
Creates an event handler than exits the application on button click.
Parameters
btn : The button that is clicked to launch the event.
Definition at line 365 of file Main.java.
Referenced by application.Main.createExitButton().
void application.Main.activateImportXMLButton (Button btn)
Activates the Import XML Button
Parameters
btn The import XML Button
Definition at line 378 of file Main.java.
References application.Main.activateErrorPage(), application.CellXMLReader.loadAndParseXMLFile(), and application.CellXMLReader.populateCellListFromDocument().
Referenced by application.Main.createImportXMLButton().
void application.Main.activatePauseAnimationButton (Button btn) private
Method for activating button that will pause animation
Parameters
btn The button that is clicked to launch the event.
Definition at line 415 of file Main.java.
References application.ApplicationConstants.gridEditable.
Referenced by application.Main.createPauseButton().
void application.Main.activateResumeAnimationButton (Button btn) private
Method for activating button that will resume animation after pause
Parameters
btn The button that is clicked to launch the event.
Definition at line 429 of file Main.java.
References application.ApplicationConstants.gridEditable.
Referenced by application.Main.createResumeButton().
void application.Main.activateReturntoStart (Button btn) private
Method to activate button that returns to start screen
Parameters
btn The button that is clicked to launch the event.
Definition at line 443 of file Main.java.
References application.Main.start().
Referenced by application.Main.createReturnToStartButton().
void application.Main.activateStartButton (Button btn, Stage stage)
Creates an event handler that launches the game on button click.
Parameters
btn : The button that is clicked to launch the event.
Definition at line 346 of file Main.java.
References application.Main.playGame().
Referenced by application.Main.createStartGameButton().
void application.Main.activateStepThroughFrame (Button btn) private
Activate button that goes through one frame when clicked
Parameters
btn The button that is clicked to launch the event.
Definition at line 458 of file Main.java.
References application.ApplicationLoop.updateGameLoop().
Referenced by application.Main.createStepThroughButton().
Button application.Main.createButton (String content, int x_Coord, int y_Coord, Group root) private
Creates a button
Parameters
content : What the button says
x_Coord : The x position of the button on the application
y_Coord : The y position of the button on the application
Returns
: Returns the newly created button
Definition at line 151 of file Main.java.
Referenced by application.Main.createExitButton(), application.Main.createImportXMLButton(), application.Main.createPauseButton(), application.Main.createResumeButton(), application.Main.createReturnToStartButton(), application.Main.createStartGameButton(), and application.Main.createStepThroughButton().
void application.Main.createErrorMessage (Group root) private
Method for creating text display for XML error message
Parameters
root the stack that holds all scenes modules
Definition at line 311 of file Main.java.
References application.Main.createLabel(), application.ApplicationConstants.ERROR_LABEL_X_POS, application.ApplicationConstants.TITLE_FONT_SIZE, and application.ApplicationConstants.TITLE_LABEL_Y_POS.
Referenced by application.Main.populateErrorPageModules().
void application.Main.createExitButton (Group root) private
Method for creating the exit button
Parameters
root the stack that holds all scenes modules
Definition at line 241 of file Main.java.
References application.Main.activateExitAppButton(), application.Main.createButton(), application.ApplicationConstants.MODULE_X_POS, and application.ApplicationConstants.SECOND_BUTTON_Y_POS.
Referenced by application.Main.populateErrorPageModules(), application.Main.populateGridPageModules(), and application.Main.populateStartPageModules().
void application.Main.createGameGraph (Group root) private
Creates a linechart for the application and populates with data
Parameters
root The group the linechart module belongs to
Definition at line 335 of file Main.java.
References application.Main.createLineChart(), application.ApplicationConstants.LINECHART_Y_POS, application.ApplicationConstants.MODULE_X_POS, and application.ApplicationLoop.populateLineChart().
Referenced by application.Main.populateGridPageModules().
void application.Main.createImportXMLButton (Group root) private
Method for creating button to import XML file
Parameters
root the stack that holds all scenes modules
Definition at line 250 of file Main.java.
References application.Main.activateImportXMLButton(), application.Main.createButton(), application.ApplicationConstants.MODULE_X_POS, and application.ApplicationConstants.THIRD_BUTTON_Y_POS.
Referenced by application.Main.populateStartPageModules().
Label application.Main.createLabel (String content, int font_size, int x_Coord, int y_Coord, Group root) private
Creates a label
Parameters
content The text that is to be displayed
font_size Font size
x_Coord x position of label
y_Coord y position of label
root:the stack that holds all scenes modules
Returns
Definition at line 194 of file Main.java.
Referenced by application.Main.createErrorMessage(), application.Main.createNameLabel(), application.Main.createSliderLabel(), and application.Main.createTitleLabel().
LineChart application.Main.createLineChart (String title, int x_Coord, int y_Coord, Group root) private
Creates and populates a line chart
Parameters
title The title of the line chart
x_Coord The x coordinate of the line chart
y_Coord The y coordinate of the line chart
root The group the line chart belongs to
Returns
: A newly initialized line chart
Definition at line 214 of file Main.java.
Referenced by application.Main.createGameGraph().
void application.Main.createNameLabel (Group root) private
Create text display for the authors of project
Parameters
root the stack that holds all scenes modules
Definition at line 319 of file Main.java.
References application.Main.createLabel(), application.ApplicationConstants.NAMES_FONT_SIZE, application.ApplicationConstants.NAMES_LABEL_X_POS, and application.ApplicationConstants.NAMES_LABEL_Y_POS.
Referenced by application.Main.populateStartPageModules().
void application.Main.createPauseButton (Group root) private
Method for creating button to pause animation
Parameters
root the stack that holds all scenes modules
Definition at line 268 of file Main.java.
References application.Main.activatePauseAnimationButton(), application.Main.createButton(), application.ApplicationConstants.MODULE_X_POS, and application.ApplicationConstants.THIRD_BUTTON_Y_POS.
Referenced by application.Main.populateGridPageModules().
void application.Main.createResumeButton (Group root) private
Method for creating button to resume animation
Parameters
root the stack that holds all scenes modules
Definition at line 277 of file Main.java.
References application.Main.activateResumeAnimationButton(), application.Main.createButton(), application.ApplicationConstants.FOURTH_BUTTON_Y_POS, and application.ApplicationConstants.MODULE_X_POS.
Referenced by application.Main.populateGridPageModules().
void application.Main.createReturnToStartButton (Group root) private
Method for creating button to return to start menu
Parameters
root the stack that holds all scenes modules
Definition at line 259 of file Main.java.
References application.Main.activateReturntoStart(), application.Main.createButton(), application.ApplicationConstants.FIRST_BUTTON_Y_POS, and application.ApplicationConstants.MODULE_X_POS.
Referenced by application.Main.populateErrorPageModules(), and application.Main.populateGridPageModules().
Slider application.Main.createSlider (int minValue, int maxValue, int x_Coord, int y_Coord, Group root) private
Method to create the slider for animation speed
Parameters
minValue smallest value of slider
maxValue largest value of slider
x_Coord x position of slider
y_Coord y position of slider
root the stack that holds all scenes modules
Returns
Definition at line 170 of file Main.java.
References application.ApplicationConstants.DEFAULT_FRAME_RATE, and application.Main.setSliderEventListener().
Referenced by application.Main.createSlider(), and application.Main.populateGridPageModules().
void application.Main.createSlider (Group root) private
Method for creating and setting the slider's max and min values as well as coordinate position
Parameters
root the stack that holds all scenes modules
Definition at line 303 of file Main.java.
References application.Main.createSlider(), application.ApplicationConstants.MODULE_X_POS, application.ApplicationConstants.SLIDER_MAX_VALUE, application.ApplicationConstants.SLIDER_MIN_VALUE, and application.ApplicationConstants.SLIDER_Y_POS.
void application.Main.createSliderLabel (Group root) private
Method for creating the text label for the slider
Parameters
root
Definition at line 295 of file Main.java.
References application.Main.createLabel(), application.ApplicationConstants.LABEL_FONT_SIZE, application.ApplicationConstants.MODULE_X_POS, and application.ApplicationConstants.SLIDER_LABEL_Y_POS.
Referenced by application.Main.populateGridPageModules().
void application.Main.createStartGameButton (Group root) private
Method for creating the start button
Parameters
root the stack that holds all scenes modules
Definition at line 232 of file Main.java.
References application.Main.activateStartButton(), application.Main.createButton(), application.ApplicationConstants.FIRST_BUTTON_Y_POS, and application.ApplicationConstants.MODULE_X_POS.
Referenced by application.Main.populateStartPageModules().
void application.Main.createStepThroughButton (Group root) private
Method for creating button to button to allow for stepping through frames
Parameters
root the stack that holds all scenes modules
Definition at line 286 of file Main.java.
References application.Main.activateStepThroughFrame(), application.Main.createButton(), application.ApplicationConstants.FIFTH_BUTTON_Y_POS, and application.ApplicationConstants.MODULE_X_POS.
Referenced by application.Main.populateGridPageModules().
void application.Main.createTitleLabel (Group root) private
Create text display for title of project
Parameters
root the stack that holds all scenes modules
Definition at line 327 of file Main.java.
References application.ApplicationConstants.BIGGER_TITLE_FONT_SIZE, application.Main.createLabel(), application.ApplicationConstants.TITLE_LABEL_X_POS, and application.ApplicationConstants.TITLE_LABEL_Y_POS.
Referenced by application.Main.populateStartPageModules().
static void application.Main.main (String[] args) static
Launches the program
Parameters
args
Definition at line 471 of file Main.java.
void application.Main.playGame (Stage stage) private
Creates and displays the game's main scene. Runs the game loop.
Definition at line 58 of file Main.java.
References application.ApplicationConstants.DEFAULT_FRAME_RATE, application.ApplicationLoop.getRoot(), application.ApplicationLoop.init(), application.Main.populateGridPageModules(), application.Main.populateStage(), application.Main.runGameLoop(), application.ApplicationConstants.STAGE_HEIGHT, and application.ApplicationConstants.STAGE_WIDTH.
Referenced by application.Main.activateStartButton().
void application.Main.populateErrorPageModules (Group root) private
Creates the error display
Parameters
root the stack that holds all scenes modules
Definition at line 134 of file Main.java.
References application.Main.createErrorMessage(), application.Main.createExitButton(), and application.Main.createReturnToStartButton().
Referenced by application.Main.activateErrorPage().
void application.Main.populateGridPageModules (Group root) private
Initiates all the modules to be displayed
Parameters
root the stack that holds all scenes modules
Definition at line 119 of file Main.java.
References application.Main.createExitButton(), application.Main.createGameGraph(), application.Main.createPauseButton(), application.Main.createResumeButton(), application.Main.createReturnToStartButton(), application.Main.createSlider(), application.Main.createSliderLabel(), and application.Main.createStepThroughButton().
Referenced by application.Main.playGame().
void application.Main.populateStage (Stage stage, Scene scene) private
Populates and shows the stage.
Parameters
scene : The application's current scene.
Definition at line 97 of file Main.java.
Referenced by application.Main.activateErrorPage(), application.Main.playGame(), and application.Main.start().
void application.Main.populateStartPageModules (Group root) private
Create modules for the start page
Parameters
root The stack that holds all scenes modules
Definition at line 107 of file Main.java.
References application.Main.createExitButton(), application.Main.createImportXMLButton(), application.Main.createNameLabel(), application.Main.createStartGameButton(), and application.Main.createTitleLabel().
Referenced by application.Main.start().
void application.Main.runGameLoop (Double speed) private
Runs the game loop and the animation that goes along with the game loop.
Definition at line 69 of file Main.java.
References application.ApplicationLoop.start().
Referenced by application.Main.playGame(), and application.Main.setSliderEventListener().
void application.Main.setSliderEventListener (Slider slider) private
Method for getting value of slider when mouse is let go
Parameters
slider slider for controlling frame rate
Definition at line 401 of file Main.java.
References application.ApplicationConstants.gridEditable, and application.Main.runGameLoop().
Referenced by application.Main.createSlider().
void application.Main.start (Stage primaryStage)
Starts the program and initializes the splash page
Definition at line 45 of file Main.java.
References application.Main.populateStage(), application.Main.populateStartPageModules(), application.Main.primaryStage, application.ApplicationConstants.STAGE_HEIGHT, and application.ApplicationConstants.STAGE_WIDTH.
Referenced by application.Main.activateReturntoStart().
Member Data Documentation
Timeline application.Main.animation private
Definition at line 38 of file Main.java.
CellXMLReader application.Main.cellXMLReader private
Definition at line 39 of file Main.java.
ApplicationLoop application.Main.myGame private
Definition at line 36 of file Main.java.
Stage application.Main.primaryStage private
Definition at line 37 of file Main.java.
Referenced by application.Main.start().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/Main.java