cellsociety_team09: application.WaTorCell Class Reference
application.WaTorCell Class Reference
Public Member Functions
WaTorCell ()
WaTorCell (int ftb, int stb, int std)
Public Member Functions inherited from application.Cell
void setThreshold (double num)
String toString ()
Protected Member Functions
void updateCell (int i, int j, Cell[][] cellMatrix)
Protected Member Functions inherited from application.Cell
abstract void updateCell (int i, int j, Cell[][] cellMatrix)
List findWantedNeighbors (Color color)
List findWantedNeighbors (Color currentColor, Color updatedColor)
List findWantedNeighbors (Cell otherCell, Color currentColor, Color updatedColor)
Private Member Functions
void updateThisCell ()
void sharkUpdate ()
void fishUpdate ()
void eatFish ()
void moveShark ()
void moveFish ()
void sharkCheck (WaTorCell waTorCell)
void fishCheck (WaTorCell waTorCell)
void killShark (WaTorCell waTorCell)
void breed (WaTorCell waTorCell, Color color)
int randomFinder (List< WaTorCell > moveFishList2)
Private Attributes
int fishTillBreed =3
int sharkTillDeath =6
int sharkTillBreed =6
int fishBreed = fishTillBreed
int sharkDeath = sharkTillDeath
int sharkBreed = sharkTillBreed
List< WaTorCell > moveFishList = new ArrayList<WaTorCell>()
List< WaTorCell > eatFishList = new ArrayList<WaTorCell>()
List< WaTorCell > moveSharkList = new ArrayList<WaTorCell>()
List< WaTorCell > breedList = new ArrayList<WaTorCell>()
Additional Inherited Members
Package Functions inherited from application.Cell
void update ()
void setCurrentState (Color color)
void setXPos (int x)
void setYPos (int y)
void setGridEdgeType (String s)
void setGridLocationShape (String s)
Package Attributes inherited from application.Cell
int xPos
int yPos
Paint currentState
Paint updatedState
double threshold
String gridEdgeType
String gridLocationShape
Cell[][] Matrix
Map< Integer, Cell > neighbors = new HashMap<Integer, Cell>()
int cellID
Detailed Description
Version 1 Date: 9/14/2014
Author
Michael Deng
Pranava Raparla
David Zhang
Definition at line 17 of file WaTorCell.java.
Constructor & Destructor Documentation
application.WaTorCell.WaTorCell ()
Constructors
Definition at line 35 of file WaTorCell.java.
References application.WaTorCell.fishTillBreed, application.WaTorCell.sharkTillBreed, and application.WaTorCell.sharkTillDeath.
application.WaTorCell.WaTorCell (int ftb, int stb, int std)
Definition at line 42 of file WaTorCell.java.
Member Function Documentation
void application.WaTorCell.breed (WaTorCell waTorCell, Color color) private
Breed either the shark or the fish
Parameters
waTorCell The cell the shark or fish moved to
color The identification of either a shark or a fish
Definition at line 187 of file WaTorCell.java.
References application.Cell.findWantedNeighbors(), application.WaTorCell.fishBreed, application.WaTorCell.fishTillBreed, application.WaTorCell.randomFinder(), application.WaTorCell.sharkBreed, application.WaTorCell.sharkTillBreed, application.WaTorCell.sharkTillDeath, and application.Cell.updatedState.
Referenced by application.WaTorCell.fishCheck(), and application.WaTorCell.sharkCheck().
void application.WaTorCell.eatFish () private
Find the fish neighbors and eat them
Definition at line 96 of file WaTorCell.java.
References application.Cell.currentState, application.WaTorCell.sharkCheck(), application.WaTorCell.sharkTillDeath, and application.Cell.updatedState.
Referenced by application.WaTorCell.sharkUpdate().
void application.WaTorCell.fishCheck (WaTorCell waTorCell) private
Checks if the fish should breed or do nothing
Parameters
waTorCell The cell the fish has moved to
Definition at line 166 of file WaTorCell.java.
References application.WaTorCell.breed().
Referenced by application.WaTorCell.moveFish().
void application.WaTorCell.fishUpdate () private
Moves the fish
Definition at line 89 of file WaTorCell.java.
References application.WaTorCell.moveFish().
Referenced by application.WaTorCell.updateThisCell().
void application.WaTorCell.killShark (WaTorCell waTorCell) private
Kills the shark if its time for him to die
Parameters
waTorCell The cell the shark moved to
Definition at line 176 of file WaTorCell.java.
References application.WaTorCell.sharkBreed, application.WaTorCell.sharkDeath, application.WaTorCell.sharkTillBreed, application.WaTorCell.sharkTillDeath, and application.Cell.updatedState.
Referenced by application.WaTorCell.sharkCheck().
void application.WaTorCell.moveFish () private
Moves the fish to a free location and then checks it breed status
Definition at line 132 of file WaTorCell.java.
References application.Cell.findWantedNeighbors(), application.WaTorCell.fishBreed, application.WaTorCell.fishCheck(), application.WaTorCell.randomFinder(), and application.Cell.updatedState.
Referenced by application.WaTorCell.fishUpdate().
void application.WaTorCell.moveShark () private
Moves the shark to a free location and then checks its breed and death statuses
Definition at line 109 of file WaTorCell.java.
References application.Cell.findWantedNeighbors(), application.WaTorCell.randomFinder(), application.WaTorCell.sharkBreed, application.WaTorCell.sharkCheck(), application.WaTorCell.sharkDeath, and application.Cell.updatedState.
Referenced by application.WaTorCell.sharkUpdate().
int application.WaTorCell.randomFinder (List< WaTorCell > moveFishList2) private
Creates a random integer that selects an index in the inputted array
Parameters
moveFishList2 The list that is being referenced
Returns
: The index of the array selected
Definition at line 206 of file WaTorCell.java.
References application.ApplicationConstants.rand.
Referenced by application.WaTorCell.breed(), application.WaTorCell.moveFish(), and application.WaTorCell.moveShark().
void application.WaTorCell.sharkCheck (WaTorCell waTorCell) private
Checks if the shark should die or breed or do nothing
Parameters
waTorCell The cell the shark has moved to
Definition at line 153 of file WaTorCell.java.
References application.WaTorCell.breed(), and application.WaTorCell.killShark().
Referenced by application.WaTorCell.eatFish(), and application.WaTorCell.moveShark().
void application.WaTorCell.sharkUpdate () private
Have the shark eat the fish around it or move if there are not fish
Definition at line 76 of file WaTorCell.java.
References application.WaTorCell.eatFish(), application.Cell.findWantedNeighbors(), and application.WaTorCell.moveShark().
Referenced by application.WaTorCell.updateThisCell().
void application.WaTorCell.updateCell (int i, int j, Cell cellMatrix[][]) protected
Updates the cell state
Definition at line 52 of file WaTorCell.java.
References application.Cell.updatedState, application.WaTorCell.updateThisCell(), application.Cell.xPos, and application.Cell.yPos.
void application.WaTorCell.updateThisCell () private
Selects the cell type and updates it
Definition at line 63 of file WaTorCell.java.
References application.Cell.currentState, application.WaTorCell.fishUpdate(), application.WaTorCell.sharkUpdate(), and application.Cell.updatedState.
Referenced by application.WaTorCell.updateCell().
Member Data Documentation
List<WaTorCell> application.WaTorCell.breedList = new ArrayList<WaTorCell>() private
Definition at line 30 of file WaTorCell.java.
List<WaTorCell> application.WaTorCell.eatFishList = new ArrayList<WaTorCell>() private
Definition at line 28 of file WaTorCell.java.
int application.WaTorCell.fishBreed = fishTillBreed private
Definition at line 23 of file WaTorCell.java.
Referenced by application.WaTorCell.breed(), and application.WaTorCell.moveFish().
int application.WaTorCell.fishTillBreed =3 private
Definition at line 19 of file WaTorCell.java.
Referenced by application.WaTorCell.breed(), and application.WaTorCell.WaTorCell().
List<WaTorCell> application.WaTorCell.moveFishList = new ArrayList<WaTorCell>() private
Definition at line 27 of file WaTorCell.java.
List<WaTorCell> application.WaTorCell.moveSharkList = new ArrayList<WaTorCell>() private
Definition at line 29 of file WaTorCell.java.
int application.WaTorCell.sharkBreed = sharkTillBreed private
Definition at line 25 of file WaTorCell.java.
Referenced by application.WaTorCell.breed(), application.WaTorCell.killShark(), and application.WaTorCell.moveShark().
int application.WaTorCell.sharkDeath = sharkTillDeath private
Definition at line 24 of file WaTorCell.java.
Referenced by application.WaTorCell.killShark(), and application.WaTorCell.moveShark().
int application.WaTorCell.sharkTillBreed =6 private
Definition at line 21 of file WaTorCell.java.
Referenced by application.WaTorCell.breed(), application.WaTorCell.killShark(), and application.WaTorCell.WaTorCell().
int application.WaTorCell.sharkTillDeath =6 private
Definition at line 20 of file WaTorCell.java.
Referenced by application.WaTorCell.breed(), application.WaTorCell.eatFish(), application.WaTorCell.killShark(), and application.WaTorCell.WaTorCell().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team09/repository/src/application/WaTorCell.java